'use client';

import { ImagePlus, Save, Trash2 } from 'lucide-react';
import { useEffect, useRef, useState } from 'react';
import useSWR, { mutate } from 'swr';
import { Avatar } from '@/components/doc-campus-shell';
import { getSummary, updateProfile, User } from '@/lib/doc-campus-api';

export function ProfileEditor({ profile, onClose }: { profile: User; onClose: () => void }) {
  const summary = useSWR('/api/users/me/summary', getSummary); const [bio, setBio] = useState(profile.bio || ''); const [avatar, setAvatar] = useState<File | undefined>(); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [removeAvatar, setRemoveAvatar] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const inputRef = useRef<HTMLInputElement>(null);
  useEffect(() => () => { if (previewUrl) URL.revokeObjectURL(previewUrl); }, [previewUrl]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { const updated = await updateProfile({ bio, avatar, removeAvatar }); await mutate('/api/users/me/summary', updated, { revalidate: false }); await mutate(`/api/users/${profile.username}`, (current: User | undefined) => current ? { ...current, ...updated } : updated, { revalidate: false }); await summary.mutate(updated, false); onClose(); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not update profile'); } finally { setBusy(false); } }
  return <div className="profile-editor"><div className="editor-avatar"><Avatar username={profile.username} src={removeAvatar ? null : previewUrl || profile.avatarUrl} large /><div><strong>Profile picture</strong><small>JPG, PNG, or WebP</small><div className="editor-actions"><button type="button" className="primary-button" onClick={() => inputRef.current?.click()}><ImagePlus size={15} /> Change photo</button><button type="button" className="secondary-button" onClick={() => { setRemoveAvatar(true); setAvatar(undefined); setPreviewUrl(null); }}><Trash2 size={14} /> Remove</button><input ref={inputRef} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={(event) => { const file = event.target.files?.[0]; if (!file) return; setAvatar(file); setRemoveAvatar(false); setPreviewUrl(URL.createObjectURL(file)); }} /></div></div></div><form onSubmit={submit}><label>Username<input value={profile.username} disabled /></label><label>About / bio<textarea value={bio} onChange={(event) => setBio(event.target.value)} maxLength={280} placeholder="Tell people what you are learning..." /><small>{bio.length}/280</small></label>{error && <p className="form-error">{error}</p>}<div className="editor-footer"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy}>{busy ? 'Saving...' : 'Save changes'} <Save size={15} /></button></div></form></div>;
}
